require: rubocop-rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false


Metrics/BlockLength:
  Enabled: false
